baseurl = "https://example.com"
languageCode = "ja"
title = "himetani's cafe"
theme = "hemingway"
copyright = "&copy; <a href=\"https://github.com/himetani\">himetani</a> 2016"
disqusShortname = "himetani"

[params]
[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/himetani"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/himetani_cafe"
fa_icon = "fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"

[taxonomies]
tag = "tags"
